class ReportTemplates:
    """
    Templates specific for the Report Generation Module.
    """

    # 1. The Strategy: Detailed list of questions to ask the RAG system sequentially.
    # We decompose the profile into granular psychological and behavioral dimensions.
    REPORT_SECTIONS_QUESTIONS = [
        # --- Core Identity ---
        ("Core Personality (Big Five)",
         "Analyze the user's personality traits. Are they extraverted or introverted? Open to new experiences? Conscientious? Agreeable? Neurotic?"),
        ("Self-Presentation",
         "How does this person present themselves to the world? Are they authentic, curated, humble, bragging, artistic, or professional?"),

        # --- Lifestyle & Routine ---
        ("Daily Routine & Habits",
         "What does a typical day look like for this person based on their posts? (e.g., morning coffee, gym, late-night parties, office work)."),
        ("Diet & Health",
         "What do they eat and drink? Do they focus on fitness, wellness, or indulgence? Any specific diet (vegan, junk food, fine dining)?"),
        ("Travel & Geography",
         "Where do they travel? Are they local explorers, luxury travelers, backpackers, or homebodies? What types of locations do they prefer (cities, nature, beaches)?"),

        # --- Interests & Passions ---
        ("Hobbies & Hard Skills",
         "What specific skills or hobbies do they demonstrate? (e.g., playing instruments, coding, painting, surfing, cooking)."),
        ("Cultural Consumption",
         "What music, movies, books, or art do they reference? What cultural events do they attend?"),
        ("Brand Affinities & Spending",
         "What brands, products, or venues appear in their content? Do they signal luxury, minimalism, streetwear, or eco-consciousness?"),

        # --- Social Dynamics ---
        ("Social Circle Analysis",
         "Who are the people around them? Do they post with a large group, a specific partner, family, or mostly alone? Is their social life chaotic or intimate?"),
        ("Relationship Status Signals",
         "Are there indications of a romantic partner, single life, or family life (children, pets)?"),

        # --- Visual & Communication ---
        ("Visual Aesthetic Code",
         "Analyze their visual language. Is it dark/moody, bright/colorful, vintage, high-tech, messy/casual, or professional?"),
        ("Caption Voice & Tone",
         "How do they write captions? Do they use emojis, long philosophical texts, short jokes, hashtags, or no text at all? What is their tone (sarcastic, inspirational, informative)?"),

        # --- Values ---
        ("Values & Beliefs",
         "What seems to matter most to them? (e.g., family, success/money, nature/environment, social justice, fun/hedonism, creativity).")
    ]

    # 2. The Compiler: Detailed structure for the final report.
    REPORT_COMPILER_SYSTEM = """
    You are a Senior Profiler and Intelligence Analyst.
    Your task is to compile a highly detailed "Psychological & Lifestyle Profile Report" based on the provided research notes.

    Input Data:
    - User Metadata (Username, Bio, Stats).
    - A series of detailed "Research Findings" generated by querying the vector database.

    Instructions:
    1. Deep Synthesis: Look for patterns across different findings (e.g., connection between 'Visual Aesthetic' and 'Personality').
    2. No Fluff: Be direct. Use bullet points for readability.
    3. Psychological Depth: Go beyond surface level. Infer *why* they post what they post.
    4. Objectivity: Maintain a professional, neutral tone.
    5. Handling Missing Data: If a specific section lacks evidence, mark it as "Insufficient Data" or omit it, do not invent facts.

    Output Format (Markdown):
    # 🕵️‍♂️ Profile Analysis: @{username}
    **Subject:** {full_name}
    **Followers:** {followers}
    **Date:** {date}

    ---

    ## 1. 📋 Executive Summary
    (A powerful, 3-5 sentence summary defining the user's archetype. E.g., "The user is a high-net-worth individual focused on luxury travel..." or "The user is a creative professional with a chaotic but authentic lifestyle...").

    ## 2. 🧠 Psychological Profile
    * **Traits:** (Big Five analysis, emotional baseline).
    * **Self-Image:** (How they want to be perceived vs. probable reality).
    * **Values:** (What drives them: Status, Freedom, Community, Art, etc.).

    ## 3. 🎨 Lifestyle & Routine
    * **Daily Life:** (Habits, work-life balance, recurring locations).
    * **Health & Diet:** (Food choices, fitness activity).
    * **Travel:** (Frequency, style, favorite destinations).

    ## 4. 🎸 Interests & Consumption
    * **Passions:** (Main hobbies and skills).
    * **Brand Affinity:** (Brands they use/wear, estimated spending power).
    * **Cultural Signals:** (Music, art, events).

    ## 5. 👥 Social Dynamics
    * **Circle:** (Close friends vs. large crowds, family presence).
    * **Status:** (Single, taken, parent, pet owner).

    ## 6. 👁️ Visual & Verbal Signature
    * **Aesthetic:** (Colors, filters, composition style).
    * **Voice:** (Caption style, emoji usage, communication tone).
    """

    REPORT_COMPILER_USER = """
    Here are the Research Findings from the RAG system:
    {research_data}

    Please compile the Deep Profile Report now.
    """